### ISSUE TITLE
fecha de los datos

### ISSUE THREAD

**Issue by 51114u9** [mauforonda/elecciones2020#1]
Viendo el mapa me puse a pensar, ¿de qué fecha y hora serán estos datos? 

En el script se podría mostrar el nombre del archivo que lees los datos:
`votos = pd.read_csv('datos/'+sorted(os.listdir('datos'))[-1])`

**Comment by mauforonda** [comment]
Gracias por la idea. Tienes razón, es importante señalar la hora y fecha de los datos, así que he modificado el cuadro de atribución de la siguiente manera:
 
![image909](https://user-images.githubusercontent.com/4010711/96661077-3fc64280-1319-11eb-84d9-83718a3a82e5.png)

**Comment by 51114u9** [comment]
la atribución a osm debería quedar y quizá esta vez leaflet quitarlo. quedo bien.

**Comment by mauforonda** [comment]
Yep, de acuerdo. No encontré una manera fácil de remover `Leaflet` de la atribución, así que la segunda mejor opción es:

![image877](https://user-images.githubusercontent.com/4010711/96664402-bfa3db00-1320-11eb-8a2e-be16c1e0d5c9.png)

:smiley:

**Comment by 51114u9** [comment]
genial, muy bien
