### ISSUE TITLE
fondo del mapa con Carto Positron

### ISSUE THREAD

**Issue by 51114u9** [mauforonda/elecciones2020#2]
Pienso que un mejor fondo del mapa es [Carto Positron](https://carto.com/help/building-maps/basemap-list/), porque muestra el mapa más actualizado, se ven los parques nacionales, se ven los límites de municipios y los nombres de barrios que cargamos en OSM se muestran con mejor fuente y tamaño según cantidad de población.

con Carto Positron:
![2](https://user-images.githubusercontent.com/1282371/96900474-abc3ba80-1481-11eb-91cf-c82bd5395288.png)

con Mapbox Light (actual):
![1](https://user-images.githubusercontent.com/1282371/96900632-d9106880-1481-11eb-9007-e722ed597dd4.png)

En el código utilicé:
`tiles = "https://{s}.basemaps.cartocdn.com/rastertiles/light_all/{z}/{x}/{y}.png",`

Se podría poner el mismo tile en las otros mapas de 2019

**Comment by mauforonda** [comment]
Tienes mucha razón, el fondo que sugieres es mucho más apropiado, ya hice el cambio gracias! :smiley:

**Comment by 51114u9** [comment]
genial. estuve viendo el commit  #c0a6f73 y no necesita el access_token, igual no es crítico
